// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.conversations.conversation_storage').requires('plusplus.entities.conversation', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityConversation_storage = ig.global.EntityConversation_storage = ig.EntityConversation.extend({
      pausing: true,
      initProperties: function() {
        this.parent();
        this.addStep("Oh, sorry. Didn't know there was someone in here.", "player");
        this.addStep("Nevermind. You can help me looking through this stuff.", "navigator");
        this.addStep("You are... a little girl?", "player");
        this.addStep("And the best navigator on this side of the galaxy.", "navigator");
        this.addStep("I thought, after that captain, nothing could surprise you anymore.", "navigator");
        this.addStep("Thinks he's fucking Picard or somethin'.", "navigator");
        this.addStep("What exactly are you looking for?", "player");
        this.addStep("Navigation equipment. The captain has 'stored' it somewhere 'round here.", "navigator");
        return this.addStep("We ain't going anywhere without it.", "navigator");
      },
      activate: function() {
        ig.game.getEntityByName('navigator').moveToLeft();
        return this.parent();
      },
      deactivate: function() {
        ig.game.getEntityByName('navigator').moveToRight();
        return this.parent();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=conversation_storage.map
*/
