// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.conversations.conversation_intro').requires('plusplus.entities.conversation', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityConversation_intro = ig.global.EntityConversation_intro = ig.EntityConversation.extend({
      pausing: true,
      initProperties: function() {
        this.parent();
        this.addStep("So, this is the engine room.", "captain");
        this.addStep("This will be your workplace for the next 1.863 miles.", "captain");
        this.addStep("Which is not that long.", "captain");
        this.addStep("Actually, our light engine should cover the distance in about 10 seconds.", "captain");
        this.addStep("Whoa.", "player");
        this.addStep("Yeah. Try to not break anything important.", "captain");
        return this.addStep("I'll be on the bridge then.", "captain");
      },
      deactivate: function() {
        var captain;
        captain = ig.game.getEntityByName('captain');
        captain.moveTo({
          x: 230,
          y: 81
        });
        captain.moveToRight();
        return this.parent();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=conversation_intro.map
*/
