// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.conversations.conversation_bed').requires('plusplus.entities.conversation', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityConversation_bed = ig.global.EntityConversation_bed = ig.EntityConversation.extend({
      pausing: true,
      initProperties: function() {
        this.parent();
        this.addStep("Which one is my mine? They all look unused.", "player");
        return this.addStep("I'll just take this one.", "player");
      },
      deactivate: function() {
        return this.parent();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=conversation_bed.map
*/
