// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.conversations.conversation_dome').requires('plusplus.entities.conversation', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityConversation_dome = ig.global.EntityConversation_dome = ig.EntityConversation.extend({
      pausing: true,
      initProperties: function() {
        this.parent();
        this.addStep("Whoa. What a view.", "player");
        return this.addStep("I have always dreamed about this.", "player");
      },
      activate: function() {
        var player;
        player = ig.game.getEntityByName('player');
        player.moveToRight();
        player.moveToStop();
        return this.parent();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=conversation_dome.map
*/
