// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.conversations.conversation_bridge').requires('plusplus.entities.conversation', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityConversation_bridge = ig.global.EntityConversation_bridge = ig.EntityConversation.extend({
      pausing: true,
      initProperties: function() {
        this.parent();
        this.addStep("There is nothing do to in here.", "player");
        this.addStep("Yeah. He will build the Ludumia in 48 hours, he said.", "captain");
        this.addStep("Everything will be fine, he said.", "captain");
        this.addStep("Guess what? He fucked up.", "captain");
        this.addStep("Who's this mysterious 'he'?", "player");
        this.addStep("The DEVELOPER.", "captain");
        this.addStep("What a moron.", "player");
        return this.addStep("Guess I'll just enjoy the view then.", "player");
      },
      activate: function() {
        var captain;
        captain = ig.game.getEntityByName('captain');
        captain.moveToLeft();
        return this.parent();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=conversation_bridge.map
*/
