// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.entities.docking').requires('plusplus.abstractities.player', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityDocking = ig.global.EntityDocking = ig.EntityExtended.extend({
      size: {
        x: 336,
        y: 48
      },
      gravityFactor: 0,
      performance: _c.DYNAMIC,
      animSheet: new ig.AnimationSheet(_c.PATH_TO_MEDIA + 'docking.png', 336, 48),
      animSettings: {
        idleX: {
          frameTime: 1,
          sequence: [0]
        }
      },
      canFlipX: false,
      initProperties: function() {
        this.vel = {
          x: -50,
          y: 0
        };
        this.killTimer = new ig.Timer(6);
        return this.parent();
      },
      update: function() {
        this.parent();
        if (this.killTimer.delta() > 0) {
          return this.kill();
        }
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=docking.map
*/
