// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.entities.npc').requires('plusplus.abstractities.character', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityNpc = ig.global.EntityNpc = ig.Character.extend({
      name: "bob",
      size: {
        x: 9,
        y: 34
      },
      animSheet: new ig.AnimationSheet(_c.PATH_TO_MEDIA + 'player.png', 9, 34),
      animSettings: {
        idleX: {
          frameTime: 1,
          sequence: [0]
        }
      },
      ready: function() {
        this.parent();
        return this.moveToLeft();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=npc.map
*/
