// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.entities.player').requires('plusplus.abstractities.player', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityPlayer = ig.global.EntityPlayer = ig.Player.extend({
      size: {
        x: 9,
        y: 34
      },
      animSheet: new ig.AnimationSheet(_c.PATH_TO_MEDIA + 'player.png', 9, 34),
      animSettings: {
        idleX: {
          frameTime: 1,
          sequence: [0]
        }
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=player.map
*/
