// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.entities.star').requires('plusplus.entities.particle-color', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityStar = ig.global.EntityStar = ig.EntityParticleColor.extend({
      size: {
        x: 1,
        y: 1
      },
      collides: ig.EntityExtended.COLLIDES.NEVER,
      gravityFactor: 0,
      animTileOffset: 28,
      lifeDuration: 5,
      randomDoubleVel: false,
      randomVel: false,
      initProperties: function() {
        this.parent();
        return this.vel = {
          x: -100,
          y: 0
        };
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=star.map
*/
