// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.entities.star').requires('plusplus.entities.particle-color', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityStar = ig.global.EntityStar = ig.EntityParticleColor.extend({
      size: {
        x: 1,
        y: 1
      },
      collides: ig.EntityExtended.COLLIDES.NEVER,
      lifeDuration: 4,
      gravityFactor: 0,
      friction: 0,
      animTileOffset: 28,
      randomDoubleVel: false,
      randomVel: false,
      initProperties: function() {
        this.parent();
        return this.vel = {
          x: -200,
          y: 0
        };
      },
      updateDynamics: function() {
        var vx, vy;
        this.vel.y += ig.game.gravity * ig.system.tick * this.gravityFactor;
        this.updateVelocity();
        vx = this.vel.x * ig.system.tick;
        vy = this.vel.y * ig.system.tick;
        return this.handleMovementTrace({
          collision: {
            x: false,
            y: false,
            slope: false
          },
          pos: {
            x: this.pos.x + vx,
            y: this.pos.y + vy
          },
          tile: {
            x: 0,
            y: 0
          }
        });
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=star.map
*/
