// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.entities.talk').requires('plusplus.entities.conversation', 'plusplus.core.config', 'plusplus.helpers.utils').defines(function() {
    var _c, _ut;
    _c = ig.CONFIG;
    _ut = ig.utils;
    return ig.EntityTalk = ig.global.EntityTalk = ig.EntityConversation.extend({
      initProperties: function() {
        this.parent();
        this.addStep("Hello Bob.", "player");
        this.addStep("Hello Player.", "bob");
        this.addStep("Nice weather today, huh?", "player");
        return this.addStep("We're on a spaceship, moron.", "bob");
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=talk.map
*/
