// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.main').requires('plusplus.core.plusplus', 'game.levels.ship', 'plusplus.debug.debug').defines(function() {
    var game, _c;
    _c = ig.CONFIG;
    game = ig.GameExtended.extend({
      init: function() {
        this.parent();
        return this.loadLevel(ig.global.LevelShip);
      },
      inputStart: function() {
        this.parent();
        return ig.input.bind(ig.KEY.P, 'pause');
      },
      inputEnd: function() {
        this.parent();
        return ig.input.unbind(ig.KEY.P, 'pause');
      },
      respondInput: function() {
        this.parent();
        if (ig.input.pressed('pause')) {
          if (this.paused) {
            return this.unpause();
          } else {
            return this.pause();
          }
        }
      }
    });
    return ig.main('#canvas', game, 60, _c.GAME_WIDTH, _c.GAME_HEIGHT, _c.SCALE, ig.LoaderExtended);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
