// Generated by CoffeeScript 1.6.3
(function() {
  ig.module('game.main').requires('plusplus.core.plusplus', 'game.levels.test').defines(function() {
    var game, _c;
    _c = ig.CONFIG;
    game = ig.GameExtended.extend({
      init: function() {
        this.parent();
        return this.loadLevel(ig.global.LevelTest);
      }
    });
    return ig.main('#canvas', game, 60, _c.GAME_WIDTH, _c.GAME_HEIGHT, _c.SCALE, ig.LoaderExtended);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
